<x-digital-card
    id="mini_card_{{ $card->id }}_{{ uniqid() }}"
    mode="thumbnail"
    :rarity="$card->rarity_slug"
    :detailUrl="route('cards.show', $card)"
    :title="$card->is_censored ? '[CENSORED]' : $card->template->card_title"
    :game="$card->template->gameTitle->title ?? 'GAME'"
    :creator="$card->originalOwner->username ?? 'Creator'"
    :quote="$card->is_censored ? '[Content hidden pending review]' : $card->template->quote"
    :backgroundColor="$card->template->background_color"
    :borderColor="$card->template->border_color"
    :sectionColor="$card->template->section_color"
    :primaryTextColor="$card->template->primary_text_color"
    :secondaryTextColor="$card->template->secondary_text_color"
    :image="$card->is_censored ? '' : $card->template->display_photo"
    :imagePositionY="$card->template->image_position_y ?? 50"
    :wins="$card->wins"
    :losses="$card->losses"
    :lifePoints="$card->life_points"
    :integrityStat="$card->integrity_stat"
    :status="$card->status"
    :rankLevel="$card->level"
    :serialNumber="$card->serial_number"
    :year="$card->forged_at->format('Y')"
    :isCensored="$card->is_censored"
    :cardId="$card->id"
    :ownerId="$card->owner_id"
/>
